"""
Based on recho client from class
"""

import select
import socket
import sys
import datetime

host = 'localhost'
port = 50004 #new default port
size = 1024
username = 'generic'

nargs = len(sys.argv)
if nargs >1:
    host = sys.argv[1]
if nargs >2:
    port = int(sys.argv[2])

username=raw_input("Enter Username: ")

s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)

s.connect((host,port))
print 'Connected to host: %s on port %s at %s)' % (host, port, datetime.datetime.now())

Outbound = [sys.stdin,s]
timeout = 11 #[Seconds]
ChatRun=True
while ChatRun:
    Inbound, Outbound,Exceptbound = select.select([],Outbound,[],timeout)
    print Inbound
    if not Inbound:
        print 'Tick %s' %datetime.datetime.now()

    for o in Outbound:
        if o == sys.stdin:
            #handle typing
            sendText = sys.stdin.readline()
	elif o==s and sys.stdin in Outbound:
            s.send('%s says: %s' % (username, sendText))

    for x in Inbound:
        inData = x.recv(size)
        if inData:
            print inData
        else:
            x.close
            #generated by select, select is given a blank list, don't need to remove
            
        
                   
            
            
